version: "3.9"

services:
  api:
    build:
        context: .
        dockerfile: "SearchAPI/Dockerfile"
    image: wackyglow/
    volumes:
        - C:\\DLS:/data
    deploy:
      replicas: 2
    depends_on:
      - balancer
  web:
    build:
        context: .
        dockerfile: "WebSearch/Dockerfile"
    ports:
        - "9002-9010:80"
  balancer:
    build:
      context: .
      dockerfile: "LoadBalancer/Dockerfile"
    ports:
      - "9011:80"
  searchstatsapi:
    build:
        context: .
        dockerfile: "SearchStatistics/Dockerfile"
    volumes:
        - C:\\DLS:/data
    ports:
      - "9012:80"
