version: "3.9"

services:
  api:
    build:
        context: .
        dockerfile: "SearchAPI/Dockerfile"
    ports:
        - 9000:80
    volumes:
        - C:\\DLS:/data
    deploy:
      replicas: 1
  web:
    build:
        context: .
        dockerfile: "WebSearch/Dockerfile"
    ports:
        - 9002:80
    deploy:
      replicas: 1
  balancer:
    build:
      context: .
      dockerfile: "LoadBalancer/Dockerfile"
    ports:
      - 9001:80
    deploy:
      replicas: 1
